#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $SCRIPT_DIR/lib/test_methods
source $SCRIPT_DIR/lib/gpg_key_methods

# -------------------------
#  Setup dir constants
# -------------------------
SSM_SOURCE_DIR="$SCRIPT_DIR/.."
SSM_TEST_DIR=$SCRIPT_DIR
TMP_TEST_DIR=$SSM_TEST_DIR/.test_ssm
SSM_TEST_KEY_NAME_PREFIX="_SSM__TEST_KEY__SSM_"
SSM_TEST_KEY1_NAME="$SSM_TEST_KEY_NAME_PREFIX.test_key1"
SSM_TEST_KEY2_NAME="$SSM_TEST_KEY_NAME_PREFIX.test_key2"

setup_test_env
# ===========================
# TESTS BELOW HERE
# ===========================

# -------------------------
#  TEST: Add secret files
# -------------------------
start_test "Adding secret test files"
bin/add_secret_file ".secret"
bin/add_secret_file ".secret2"
test_text_in_file ".secret" "$TMP_TEST_DIR/config/secret_files"
test_text_in_file ".secret2" "$TMP_TEST_DIR/config/secret_files"
pass_test

# -------------------------
#  TEST: Import pubkey
# -------------------------
cd $TMP_TEST_DIR
start_test "Importing test key to ssm"
./bin/import_pubkey $SSM_TEST_KEY1_NAME
test_file_exists "$TMP_TEST_DIR/config/pubkeys/$SSM_TEST_KEY1_NAME.pub"
pass_test

# -------------------------
#  TEST: Encrypt secrets
# -------------------------
start_test "Encrypting secrets"
./bin/encrypt_secrets
echo "[TEST] .. Moving original .secret file to .secret.orig"
echo "[TEST] .. Moving original .secret2 file to .secret2.orig"
test_file_exists "$TMP_TEST_DIR/.secret.ssm.gpg"
test_file_exists "$TMP_TEST_DIR/.secret2.ssm.gpg"
pass_test

# -------------------------
# TEST: Decrypt secrets
# -------------------------
start_test "Decrypting secrets"
mv .secret .secret.orig
mv .secret2 .secret2.orig
bin/decrypt_secrets

echo "[TEST] Comparing encrypted/decrypted files and orig files for equality:"
echo "[TEST] original file and encrypted/decrypted files match"
test_file_equality ".secret.orig" ".secret"
test_file_equality ".secret2.orig" ".secret2"
pass_test

# -------------------------
# TEST: Decrypt secrets as other user
# - have pub/priv key precreated in test dir
# - bin/import pubkey for encryption
# - remove generated pub/priv key pair
# - import priv key
# - decrypt secrets
# -------------------------

# TODO: 
pending_test "TODO: Decrypting secrets as other user"

# -------------------------
#  Cleanup
# -------------------------
destroy_test_env