#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $SCRIPT_DIR/lib/set_up_test_harness

# ===========================
# TESTS HERE
# ===========================

# -------------------------
# TEST: Decrypt secrets
# -------------------------

### Test setup ###
ssm/bin/import_pubkey $SSM_TEST_KEY1_NAME > /dev/null
ssm/bin/add_secret_file ".secret" > /dev/null
ssm/bin/encrypt_secrets > /dev/null
git add . > /dev/null
git commit -am "commit secret 1" > /dev/null

ssm/bin/add_secret_file ".secret2" > /dev/null
ssm/bin/encrypt_secrets > /dev/null
git add . > /dev/null
git commit -am "commit secret 2" > /dev/null


### Test execution ###
start_test "Decrypting secrets"
mv .secret .secret.orig
mv .secret2 .secret2.orig
ssm/bin/decrypt_secrets

echo "[TEST] Comparing encrypted/decrypted files and orig files for equality:"
echo "[TEST] original file and encrypted/decrypted files match"
test_file_equality ".secret.orig" ".secret"
test_file_equality ".secret2.orig" ".secret2"
pass_test

# ====================================
#  Cleanup
# ====================================
destroy_test_env
