#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $SCRIPT_DIR/lib/set_up_test_harness

# ===========================
# TESTS HERE
# ===========================

# -------------------------
# TEST: Decrypt secrets as other user
# - have pub/priv key precreated in test dir
# - bin/import pubkey for encryption
# - remove generated pub/priv key pair
# - import priv key
# - decrypt secrets
# -------------------------
#ssm/bin/import_pubkey $SSM_TEST_KEY1_NAME
#ssm/bin/add_secret_file ".secret"
#ssm/bin/add_secret_file ".secret2"
#ssm/bin/encrypt_secrets

pending_test "TODO: Decrypting secrets as other user"

# ====================================
#  Cleanup
# ====================================
destroy_test_env
