#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $SCRIPT_DIR/lib/set_up_test_harness

# ===========================
# TESTS HERE
# ===========================

# -------------------------
# TEST: Add secret files
# -------------------------
require_var $TMP_TEST_SSM_INSTALL_DIR "TMP_TEST_SSM_INSTALL_DIR"

start_test "Adding secret test files"
ssm/bin/add_secret_file ".secret"
ssm/bin/add_secret_file ".secret2"
test_text_in_file ".secret" "$TMP_TEST_SSM_INSTALL_DIR/config/secret_files"
test_text_in_file ".secret2" "$TMP_TEST_SSM_INSTALL_DIR/config/secret_files"
pass_test

# ====================================
#  Cleanup
# ====================================
destroy_test_env
