#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $SCRIPT_DIR/lib/set_up_test_harness

# ===========================
# TESTS HERE
# ===========================

# -------------------------
#  TEST: Encrypt secrets
# -------------------------

### Test setup ###
ssm/bin/import_pubkey $SSM_TEST_KEY1_NAME > /dev/null
ssm/bin/add_secret_file ".secret" > /dev/null
ssm/bin/add_secret_file ".secret2" > /dev/null


### Test execution ###
start_test "Encrypting secrets"
ssm/bin/encrypt_secrets
echo "[TEST] .. Moving original .secret file to .secret.orig"
echo "[TEST] .. Moving original .secret2 file to .secret2.orig"
test_file_exists "$TMP_TEST_DIR/.secret.ssm.gpg"
test_file_exists "$TMP_TEST_DIR/.secret2.ssm.gpg"
pass_test

# ====================================
#  Cleanup
# ====================================
destroy_test_env
