#!/usr/bin/env bash
# Author: Søren Houen
# License: LGPL 3.0 https://www.gnu.org/licenses/lgpl-3.0.en.html
TEST_METHODS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$TEST_METHODS_SCRIPT_DIR/gpg_key_methods"
source "$TEST_METHODS_SCRIPT_DIR/../../lib/require_var"

function start_test {
   require_var $TMP_TEST_DIR "TMP_TEST_DIR"
   
   cd $TMP_TEST_DIR
   echo ""
   echo -e "\033[1;36m==============================="
   echo "[TEST] $1"
   echo "==============================="
   echo -e "\033[1;37m"
}

function pending_test {
   echo ""
   echo -e "\033[1;33m==============================="
   echo "[PENDING TEST] $1"
   echo "==============================="
   echo -e "\033[1;37m"
}

function fail_test {
   echo ""
   echo -e "\033[1;31m==============================="
   echo "[FAIL]" $1
   echo "==============================="
   echo -e "\033[1;37m"
   exit 1
}

function pass_test {
   echo ""
   echo -e "\033[1;32m==============================="
   echo "[PASS]"
   echo "==============================="
   echo -e "\033[1;37m"
   echo ""
}

function test_file_exists {
   if [ ! -f $1 ]; then
      fail_test "File does not exist: $1"
   fi
}

function test_file_equality {
   cmp -s $1 $2 || fail_test "Files are not equal: $1 != $2"
}

function test_text_in_file {
   text=$1
   file=$2
   grep -Fx "$text" $file || fail_test "Text '$text' is not in file $file"
}

function destroy_test_env {
   require_var $TMP_TEST_DIR "TMP_TEST_DIR"
   require_var $SSM_TEST_KEY1_NAME "SSM_TEST_KEY1_NAME"
   require_var $SSM_TEST_KEY2_NAME "SSM_TEST_KEY2_NAME"

   echo "[CLEANUP] Removing test dir ($TMP_TEST_DIR)"
   rm -Rf $TMP_TEST_DIR
   echo "[CLEANUP] Removing temporary gpg keys:"
   delete_gpg_key $SSM_TEST_KEY1_NAME >/dev/null 2>&1
   delete_gpg_key $SSM_TEST_KEY2_NAME >/dev/null 2>&1
}
