#!/usr/bin/env bash
# Author: Søren Houen
# License: LGPL 3.0 https://www.gnu.org/licenses/lgpl-3.0.en.html

function get_latest_ssm_version {
  latest_release_tag=$(curl -s https://api.github.com/repos/houen/ssm/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
  echo $latest_release_tag
}
