#!/usr/bin/env bash
# Author: Søren Houen
# License: LGPL 3.0 https://www.gnu.org/licenses/lgpl-3.0.en.html

function require_var {
  if [ -z $1 ] || [ -z $2 ]; then
    echo "[ERROR] Required var $1 not set!"
    exit 1
  fi
}