#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SSM_DIR="$LIB_DIR/.."
LIB_DIR="$SSM_DIR/lib"
CONFIG_DIR="$SSM_DIR/config"
PUBKEYS_DIR="$SSM_DIR/pubkeys"

# KEYS_LIST_FILE="$CONFIG_DIR/gpg_keys"
KEYS_LIST_FILE="$SSM_DIR/gpg_keys"
SECRETS_LIST_FILE="$SSM_DIR/secret_files"

function require_argument {
  if [ -z $1 ]; then
      echo "[ERROR] No argument given!"
      exit 1
  fi
}

function require_file_presence {
  require_argument $1
  if [ ! -f $1 ]; then
    echo "[ERROR] File not found!"
    exit 1
  fi
}

function import_public_keys {
  echo "[INFO] Importing public keys from $PUBKEYS_DIR:"
  for filename in $PUBKEYS_DIR/*.pub; do
    [ -e "$filename" ] || continue
    gpg -q --yes --import $filename
  done
}

# -------------------------
# Load GPG keys var
# -------------------------
file=$KEYS_LIST_FILE
if [ ! -f $file ]; then
    echo "[ERROR] $KEYS_LIST_FILE file not found!"
    exit 1
fi

# Add newline to end of file
[ -n "$(tail -c1 $file)" ] && echo >> $file
gpg_keys=()
while IFS= read -r line; do
  # If line is not a comment (starts with #)
  if  [[ $line != \#* ]] ; then  
    gpg_keys+=("$line")
  fi
done < $file # Read lines from file


# -------------------------
# Load secret files var
# -------------------------
file=$SECRETS_LIST_FILE
if [ ! -f $file ]; then
    echo "[ERROR] secret_files file not found!"
    exit 1
fi

# Add newline to end of file
[ -n "$(tail -c1 $file)" ] && echo >> $file
secret_files=()
while IFS= read -r line; do
  # If line is not a comment (starts with #)
  if  [[ $line != \#* ]] ; then
    secret_files+=("$line")
  fi
done < $file # Read lines from file