#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SSM_DIR="$SCRIPT_DIR/.."

source "$SSM_DIR/lib/constants"
source "$SSM_DIR/lib/require_argument"
source "$SSM_DIR/lib/require_file_presence"
source "$SSM_DIR/lib/import_public_keys"
source "$SSM_DIR/lib/get_latest_ssm_version"

# -------------------------
# Load GPG keys var
# -------------------------
file=$KEYS_LIST_FILE
if [ ! -f $file ]; then
    echo "[ERROR] $KEYS_LIST_FILE file not found!"
    exit 1
fi

# Add newline to end of file
[ -n "$(tail -c1 $file)" ] && echo >> $file
GPG_KEYS_FOR_ENCRYPTION=()
while IFS= read -r line; do
  # If line is not a comment (starts with #)
  if  [[ $line != \#* ]] ; then  
    GPG_KEYS_FOR_ENCRYPTION+=("$line")
  fi
done < $file # Read lines from file


# -------------------------
# Load secret files var
# -------------------------
file=$SECRETS_LIST_FILE
if [ ! -f $file ]; then
    echo "[ERROR] $SECRETS_LIST_FILE file not found!"
    exit 1
fi

# Add newline to end of file
[ -n "$(tail -c1 $file)" ] && echo >> $file
SECRET_FILES_FOR_ENCRYPTION=()
while IFS= read -r line; do
  # If line is not a comment (starts with #)
  if  [[ $line != \#* ]] ; then
    SECRET_FILES_FOR_ENCRYPTION+=("$line")
  fi
done < $file # Read lines from file
