#!/bin/bash

LIB_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SSM_DIR="$LIB_DIR/.."

function require_argument {
  if [ -z $1 ]; then
      echo "[ERROR] No argument given!"
      exit 1
  fi
}

function require_file_presence {
  require_argument $1
  if [ ! -f $1 ]; then
    echo "[ERROR] File not found!"
    exit 1
  fi
}

function import_public_keys {
  echo "[INFO] Importing public keys from $SSM_DIR/pubkeys:"
  for filename in $SSM_DIR/pubkeys/*.pub; do
    [ -e "$filename" ] || continue
    gpg -q --yes --import $filename
  done
}

# -------------------------
# Load GPG keys var
# -------------------------
file="$SSM_DIR/gpg_keys"
if [ ! -f $file ]; then
    echo "[ERROR] $SSM_DIR/gpg_keys file not found!"
    exit 1
fi

sed -i -e '$a\' $file # add newline to end of file
gpg_keys=()
while IFS= read -r line; do
  # If line is not a comment (starts with #)
  if  [[ $line != \#* ]] ; then  
    gpg_keys+=("$line")
  fi
done < $file # Read lines from file


# -------------------------
# Load secret files var
# -------------------------
file="$SSM_DIR/secret_files"
if [ ! -f $file ]; then
    echo "[ERROR] secret_files file not found!"
    exit 1
fi

sed -i -e '$a\' $file # add newline to end of file
secret_files=()
while IFS= read -r line; do
  # If line is not a comment (starts with #)
  if  [[ $line != \#* ]] ; then
    secret_files+=("$line")
  fi
done < $file # Read lines from file